### ISSUE TITLE
Build-status badge for a gcc/clang builder?

### ISSUE THREAD

**Issue by Quuxplusone** [compiler-explorer/infra#1191]
It occurs to me that it would be convenient if I could put a build-status badge on
https://github.com/Quuxplusone/llvm-project/tree/trivially-relocatable
https://github.com/Quuxplusone/gcc/tree/trivially-relocatable
showing the status of the Compiler Explorer builds for those branches (i.e. clang-relocatable and gcc-p1144). This would give me a (1) quick and (2) easy-to-remember way to check whether anything of mine was currently broken; and also, I could make the badge itself a hyperlink to the current build's results, which would again help with the "easy-to-remember" part.

I'm sure I can figure out the pretty-pictures part with help from https://shields.io/ ; but I'd like some help figuring out where the "current clang-builder build status" and "current gcc-builder build status" can be pulled from.

**Comment by partouf** [comment]
For the compilers that we build every day you can see the build-status here https://github.com/compiler-explorer/compiler-workflows/blob/main/build-status.md
