### ISSUE TITLE
Have Julia nightly toolchain

### ISSUE THREAD

**Issue by giordano** [compiler-explorer/infra#1260]
I see there are nightly versions of some toolchains in Compiler Explorer, what would we need to do to have also the [nightly version of Julia](https://julialang.org/downloads/nightlies/) in here?  Are nightly versions automatically updated periodically?

CC: @vchuravy.

**Comment by partouf** [comment]
Ok, I added the install for the nightly, will be refreshed every day and is located at `/opt/compiler-explorer/julia-nightly`
Will need an entry in the main repo in the etc/config/julia properties

**Comment by giordano** [comment]
That was quick, thanks a lot!  I presume this https://github.com/compiler-explorer/compiler-explorer/pull/6283 should be the corresponding PR for `compiler-explorer`?
