### ISSUE TITLE
Noisy SMBd

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#1334]
https://my.papertrailapp.com/events?q=program%3Asmbd

Would be nice to reduce the noise. The errors aren't really relevant.

**Comment by partouf** [comment]
So, I think this needs a recompile/reinstall of a different smbd

The logline is emitted by this macro https://github.com/samba-team/samba/blob/68f0835c8e1c5029cd831c267b75c02185b206c7/lib/util/debug.h#L197

And `MAX_DEBUG_LEVEL` should be set during compilation, otherwise this takes effect https://github.com/samba-team/samba/blob/68f0835c8e1c5029cd831c267b75c02185b206c7/lib/util/debug.h#L42

The debug level should be less than 10 https://github.com/samba-team/samba/blob/68f0835c8e1c5029cd831c267b75c02185b206c7/lib/util/debug.h#L277

**Comment by partouf** [comment]
It's still using the AMI where it just has the default Ubuntu 20 smb installed. (the `setup-smb.sh` has changed but was for testing purposes and it never amounted to anything)

When I do `smbd --build-options`, it does not reveal it was built with MAX_DEBUG_LEVEL
Maybe Ubuntu has changed the original code?

**Comment by mattgodbolt** [comment]
Got it. Thanks Partouf

**Comment by partouf** [comment]
Filtering was set up for this in Papertrail. Still a bandwidth nuisance ofc, but it's better than nothing.
Closing for now
