### ISSUE TITLE
Question about adding a compiler

### ISSUE THREAD

**Issue by Cr0a3** [compiler-explorer/infra#1440]
Hello dear compiler-explorer team,
I want to add my own compiler to compiler-explorer.
It can be installed using:
```
cargo install ylc --git https://github.com/Cr0a3/ygen.git
```
And then used:
```
ylc -in="input" -o="output.o"
```

Where do i need to add the installation step in which file?

And another question. Would this be a correct `ygen.amazon.properties` file?:
```
compilers=&ylc
defaultCompiler=ylctrunk

demangler=/opt/compiler-explorer/gcc-11.1.0/bin/c++filt
objdumper=/opt/compiler-explorer/gcc-11.1.0/bin/objdump

licenseName=Apache 2
licenseLink=https://github.com/Cr0a3/ygen/blob/main/LICENSE
licensePreamble=Ygen is licensed under the Apache License v2.0

group.ylc.compilers=ylc012:ylctrunk
group.ylc.compilerType=ylc
group.ylc.supportsExecute=false
group.ylc.intelAsm=
group.ylc.groupName=Ygens ir compiler
group.ylc.versionRe=Ygen version .*
group.ylc.isSemVer=true
group.ylc.baseName=ylc
group.ylc.options=-asm-clr

compiler.ylc012.exe=/opt/compiler-explorer/ygen-0.1.2/bin/ylc
compiler.ylc012.semver=0.1.2

compiler.ylctrunk.exe=/opt/compiler-explorer/ygen-trunk/bin/ylc
compiler.ylctrunk.semver=(trunk)
compiler.ylctrunk.objdumper=/opt/compiler-explorer/gcc-snapshot/bin/objdump
```

Sorry

Bye
Toni I.

**Comment by Cr0a3** [comment]
My skill issue

**Comment by mattgodbolt** [comment]
Hi! We don't currently support installation by `cargo` - but it's something we could add. Our main issue is whatever gets installed needs to be installed on one system but run on many more. Currently we do this by building on a CI system that creates a tarball (see for example https://github.com/compiler-explorer/misc-builder/ or https://github.com/compiler-explorer/clang-builder/ -- that would be the system that runs `cargo build`. The result of that are then installed on our base image that's then shared over the network with the many systems that run compiles.
