### ISSUE TITLE
Adding SPIRV-Cross and SPIRV-Reflect

### ISSUE THREAD

**Issue by spencer-lunarg** [compiler-explorer/infra#1444]
From https://github.com/compiler-explorer/compiler-explorer/pull/7056

I wanted to add the logic to pull down and build [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) and [SPIRV-Reflect](https://github.com/KhronosGroup/SPIRV-Reflect) so that it can be used lived

My thought was "we already do a nightly for `SPIRV-Tools` so I should be able to mostly copy that, but I can't find anything for that. I found an [old commit](https://github.com/compiler-explorer/infra/commit/0749f1a4c154be9498bfce527bcc2b7a6a62a997#diff-86be4b172d3b4b66b072f6b9cff04683e5a2cbe71ae1c1523db81a3a9239e424R137) but not sure how I am suppose to help add these 2 tools/compilers

**Comment by spencer-lunarg** [comment]
Wanted to also mention that there is a [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) that provides all of these binaries ready to go if building them is the time constraint

**Comment by mattgodbolt** [comment]
Hi @spencer-lunarg -- does the vulkan SDK "untar" into a directory or does it "install"? it looks like a tarball but is called "installer" -- effectively, if those prebuilts are "just untar and off you go" we're ready :) If not, then it's more tricky.

The clang-spirv is built here: https://github.com/compiler-explorer/clang-builder/blob/1d71d739d405379fa1d015960ab085855687497f/build/build.sh#L214-L226 (also search the rest of that file for `spirv` to find some other bits and bobs). It's possible it'll be straightforward to adapt for cross and reflect.

**Comment by spencer-lunarg** [comment]
> if those prebuilts are "just untar and off you go"

they are! The "install" is an optional step

so if you untar it there will be a folder inside with the version (ex `1.3.296.0` and from there it is just `1.3.296.0/x86_64/bin/spirv-cross` and `1.3.296.0/x86_64/bin/spirv-reflect`

**Comment by mattgodbolt** [comment]
Oh fab: that _might_ be easy to do as tarball installable in the infra then. I will try and take a look later, and see what happens.

My experience of these more exotic compilers though is they tend to have a lot of external dependencies (like SDKs etc) ... so we'll see ! :)

**Comment by mattgodbolt** [comment]
Events have overtaken me and I haven't had a chance to look at this yet. Will try and get to it by the weekend.

**Comment by mattgodbolt** [comment]
@spencer-lunarg I just posted #1475 which should let us add arbitrary vulkan SDKs. Let me know what else needs doing to test and check these compilers.
