### ISSUE TITLE
Improve compiler and library installation mechanisms

### ISSUE THREAD

**Issue by RubenRBS** [compiler-explorer/infra#183]
As discused on Slack, it would be great to have something which is a bit more clean and gives us a bit more control than the current bash setup

**Comment by mattgodbolt** [comment]
Starting to sketch some python installation for this

**Comment by mattgodbolt** [comment]
See 6edb11b4aa68251d264173c8f644eea5a3e45883, 719971b515b5a83ffda2b758956bfd33b336e7d7 and 165abe73d9ecb245ab8225eb82ffa6473ed74dc7 as a start

**Comment by mattgodbolt** [comment]
Slowly getting there. I just killed off the C++ installers. But there's a long tail of work on this.
