### ISSUE TITLE
rsync of /celibs gives errors until sync completes

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#207]
The onwership of files in `/celibs/` is only set at the end by rsync:

```
ubuntu@ip-172-30-1-18:~$ ls -l /celibs/
total 28
drwxr-xr-x 3 ubuntu ubuntu 4096 Apr 20  2017 boost_1_64_0
drwxr-xr-x 3 ubuntu ubuntu 4096 Sep  3  2017 boost_1_65_0
drwxr-xr-x 3 ubuntu ubuntu 4096 Jan 19  2018 boost_1_66_0
drwxr-xr-x 3 ubuntu ubuntu 4096 Apr 14  2018 boost_1_67_0
drwxr-xr-x 3 ubuntu ubuntu 4096 May 15 19:07 boost_1_68_0
drwx------ 2 root   root   4096 May 15 18:56 boost_1_69_0
drwx------ 2 root   root   4096 May 15 18:56 boost_1_70_0
```

(this is mid rsync)

Compiles using these files fail with permissions errors:

```
cc1plus: fatal error: /celibs/boost_1_70_0/stdc-predef.h: Permission denied
compilation terminated.
Compiler returned: 1
```

Maybe rsync to a temp dir (`boost_1_70_0.tmp` ?) and `mv` when complete to atomically make available.

**Comment by apmorton** [comment]
Seems like even if the permissions were correct during a sync you could still get errors due to missing files that haven't been synced yet?

**Comment by apmorton** [comment]
we no longer rsync boost since 141480204ca34c88ae8e637bd8b6ea7e6e6c034b
