### ISSUE TITLE
We've lost nginx error logging in papertrail

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#211]
Can't see anything in there

**Comment by apmorton** [comment]
`remote_syslog` isn't running on the nodes.

another option is to have nginx log directly to syslog (locally to rsyslogd or directly to papertrail)
http://nginx.org/en/docs/syslog.html

**Comment by apmorton** [comment]
this was fixed at some point as I can see nginx error logs in papertrail:

these are regularly logged during instance startup before the node app boots:
https://my.papertrailapp.com/events?q=%22Connection+refused%22
