### ISSUE TITLE
Move to Grafana as discussed on Slack

### ISSUE THREAD

**Issue by RabsRincon** [compiler-explorer/infra#242]
Putting this here just so it does not get forgotten. Grafana (https://grafana.com/) was suggested by @apmorton as an alternative to StatHat (https://stathat.com) which we currently use

**Comment by mattgodbolt** [comment]
Thanks for filing this! Will take a look!

**Comment by mattgodbolt** [comment]
First look: papertrail doesn't seem to support it (supports "HostedGraphite") -- but this is absolutely not a blocker. Right now I use plain-text searches from our log output in papertrail to count statistics and upload them to stathat. That's a terrible way of doing things. We should directly log metrics out :)

**Comment by apmorton** [comment]
I just signed up for a grafana cloud team to play around with - I can add any of you that would like to poke around, just ping me on slack.

It comes included with something called loki (https://grafana.com/oss/loki#about), which seems to be pretty similar to papertrail, except part of the grafana ecosystem. (I will admit despite using grafana on some past teams I have never really setup a grafana system myself).

Maybe we can start by piping our existing logs into a loki instance in addition to papertrail so we have some data to play with?

The server-side metrics would be accomplished by posting data into the prometheus or graphite instances that come as part of grafana.

**Comment by mattgodbolt** [comment]
Looks like we're using Grafana :D https://ce.grafana.com/ yay
