### ISSUE TITLE
Update Intel compiler

### ISSUE THREAD

**Issue by flamewing** [compiler-explorer/infra#277]
The current version (19.0.1) has issues with c++17 fold expressions if the output of the expression is discarded (see this [example](https://godbolt.org/z/QaHX8s); the difference between top and bottom is a cast to void of the fold expression). It seems that the newest version is [19.0.5](https://software.intel.com/en-us/articles/intel-c-compiler-190-for-linux-release-notes-for-intel-parallel-studio-xe-2019), and it fixes this issue.

**Comment by mattgodbolt** [comment]
Thanks: we will try and get hold of a new version. The installation process is...painful....so we avoid it as much as possible, unfortunately :(

**Comment by flamewing** [comment]
I am closing this one since versions 21.1.8 and 21.1.9 are now available. Thanks!
