### ISSUE TITLE
Add a clang compiler variant for pattern matching proposal

### ISSUE THREAD

**Issue by yaahc** [compiler-explorer/infra#281]
# Goal

I'd like to be able to play with the upcoming pattern matching proposal syntax and I figured that it would be cooler to be able to do it on godbolt than to just compile the working implementation on my own machine.

# Presumed info needed to move forward

The example implementation of the pattern matching proposal lives in https://github.com/dansarginson/llvm-project

I'm hoping that I can use this previous PR (https://github.com/mattgodbolt/compiler-explorer-image/pull/157/files) as a rough guide for whats necessary in this PR

----

If theres anything else thats needed to get this setup lmk, otherwise I'll hopefully dig into this sometime this week or next, unless someone else gets to it first.

**Comment by RabsRincon** [comment]
Hi
Thanks for wanting to do the heavy lifting for us and adding the compiler, we really appreciate it! :)

The PR you link to also has an accompanying PR at the sister repo which takes care of making the compiler visible in the site: https://github.com/mattgodbolt/compiler-explorer/pull/1245

You can also find some on adding a compiler here https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/AddingACompiler.md in case you need it

Other than that, please do feel free to let us know if you have any trouble in the process as the documentation is not too clear for the most part (Oops)

Again, thanks for taking the time to help bringing a new compiler to the site 👍

**Comment by yaahc** [comment]
I'm sorry, I don't think I'm ever going to get to this so I'm going to unassign myself, thank you for all the great work :heart:

**Comment by mattgodbolt** [comment]
Thanks @yaahc :) We'll see what we can do still, and appreciate your keeping us in the loop here (and for being a legendary supporter too!!)

**Comment by lenary** [comment]
I'm happy to take this on - it would be useful to know what branch of that repo I should be aiming for - `patmat`?

**Comment by lenary** [comment]
I've got a prototype, which I can aim at any branch in that repo - I notice `patmat` is 11 months old, and the others have more confusing names that I cannot interpret.

**Comment by lenary** [comment]
Deployed today! https://godbolt.org/z/h3Y857 Thanks @mattgodbolt.

This issue can now be closed, I think.

**Comment by mattgodbolt** [comment]
Yes! Thanks so much @lenary !
