### ISSUE TITLE
Daily build check for changes

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#319]
Our crappy "CI for compilers" should check to see if anything's changed. A number of the branches we build don't update all that often.

Suggestion:

* Store "build hash" document (git hash of any git sync'd repo) on s3
* Check it at build start and exit early
* and/ or get the admin-daily-builds to do this bit somehow

something like this?

We'd have to make sure our "install latest" and "keep last Y trunk builds" works (I think it does, not being based on time).

Our builder bill is one of our biggest single item after EFS costs, so reducing it seems like a good thing.

**Comment by mattgodbolt** [comment]
Current plan (such as it is) is to update from using `s3cmd` and move to `aws` (which can pick up privs etc from the outside automatically). Once done (or even before) we can have an s3 endpoint where we store a `s3://compiler-explorer/built/SHA_OF_SOURCE` or similar. If that file exists; we're done. If not, we build and then after a successful upload, we create that file.

**Comment by mattgodbolt** [comment]
(using SHA_OF_SOURCE here to pick up more than just git upstreams; and also to factor in any dependent libraries etc; basically `find . -type f | xargs shasum | shasum` or similar)

**Comment by mattgodbolt** [comment]
(with a sort or something in there too)

**Comment by apmorton** [comment]
something along these lines has been implemented for a while now, closing
