### ISSUE TITLE
nim nightlies no longer install

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#340]
The github version is missing. See nim-lang/nightlies#31

We basically grab https://api.github.com/repos/nim-lang/nightlies/releases/latest and look for the linux_x64 binaries.

**Comment by narimiran** [comment]
> We basically grab https://api.github.com/repos/nim-lang/nightlies/releases/latest and look for the linux_x64 binaries.

This should now work again.

Thanks for reporting it on the `nightlies` repo!

**Comment by mattgodbolt** [comment]
Thanks @narimiran !

**Comment by apmorton** [comment]
See https://github.com/nim-lang/nightlies/pull/40

Starting in the next day or two we should have stable URLs to grab nim nightlies for each release branch.

The asset filenames are still somewhat suspect, so we may not be able to _just_ grab from a stable URL, but at least the release name on GitHub is stable.
