### ISSUE TITLE
ispc nightly is failing

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#362]
The URL https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build/ispc-trunk-linux.tar.gz?job=Environment:%20APPVEYOR_BUILD_WORKER_IMAGE=Ubuntu1604,%20LLVM_VERSION=latest (from https://github.com/compiler-explorer/infra/blob/master/bin/yaml/ispc.yaml#L27 ) is now returning a 404

```
{"message":"Build job with specified name not found or access denied."}
```

CC @pbrubaker in case he has an idea where it might have moved to.

**Comment by pbrubaker** [comment]
It's fixed on our end now, thanks for reporting @mattgodbolt!
