### ISSUE TITLE
The Ubuntu Upgrade thing

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#376]
Ubuntu should be upgrade to v20, for every instance and all the builders.

But this _might_ have consequences.
It should be very limited, but who knows.

But I suggest we make a plan or testing ritual to do all the things to make sure we don't break anything.

Things we might wanna do;
* `docker build` upgraded images beforehand
* Write automated tests for;
  - Normal code examples for all languages
  - Executed code examples for all languages
  - Executed code examples for header only libraries
  - Executed code examples for C .so Libraries
* Conan related automated tests for;
  - Executed code examples for C++ .so libraries without upgrading library-builder
  - Executed code examples for C++ .a libraries without upgrading library-builder
  - If any fail, upgrade library-builder and force-rebuild all libraries after site upgrade, message required that libraries linking will be broken for a few weeks
  - If none fail, silently upgrade library-builder

Other things we should recognize and/or upgrade at the same time?

**Comment by partouf** [comment]
For the noscript PR a few weeks ago I started an API testing thing using approvals, which speeds up the testing quite a bit https://github.com/partouf/ce_apitest
Needs a lot more tests still

**Comment by mattgodbolt** [comment]
And we should definitely _not_ upgrade to 20.05 ;)

**Comment by mattgodbolt** [comment]
Presumably @partouf you saw the crappy thing I _used_ to use at https://github.com/compiler-explorer/infra/tree/master/test . I should probably remove that as it's old, huge and not used...

**Comment by partouf** [comment]
> Presumably @partouf you saw the crappy thing I _used_ to use at https://github.com/compiler-explorer/infra/tree/master/test . I should probably remove that as it's old, huge and not used...

Oh I did not! I assume a lot of them might be broken now

**Comment by partouf** [comment]
Ub20 is live without any obvious issues.

Have tested some libraries with https://github.com/partouf/ce_apitest - but not all. Still need to do that.

**Comment by mattgodbolt** [comment]
Am upgrading the builder (manually, in-place) now.

**Comment by mattgodbolt** [comment]
Builder is now 20.04.1, working on admin node next. Doing it in-place again just for somewhat vague fear that some of the stuff in `/home/ubuntu` might be important

**Comment by mattgodbolt** [comment]
admin box now on 20.04.1 (yay). Let me know if you'd like me to do the Conan server, @partouf

**Comment by partouf** [comment]
The conan packer could be changed and built. It doesn't really matter how it's upgraded, as long as it's announced somewhere that linking libraries will be offline for a bit during restart or stop/start. I don't really know how much cloudfront has cached to say users will or won't notice...

**Comment by partouf** [comment]
I think there was a file that will be lost when a full shutdown/restart happens.. I really need to change that.. hmm

**Comment by partouf** [comment]
We updated the main instances to ub20 a while ago and nothing has broken it seems.
