### ISSUE TITLE
Can we support ICC 19.1?

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#378]
https://software.intel.com/en-us/node/807141

Discovered via question asked here -> https://github.com/compiler-explorer/infra/issues/123#issuecomment-667073487

**Comment by rscohn2** [comment]
It's gotten much easier to install icc. You can install from oneapi hpckit. No license file is required and a script can fetch the install media directly from intel and do the install. It would be similar to the way install_cuda works in https://github.com/compiler-explorer/infra/blob/master/update_compilers/install_nonfree_compilers.sh

I can give you a PR for the changes. I would not be able to test in your environment so you might have to tweak paths to get it to work.

**Comment by partouf** [comment]
Thanks, that would be very helpful!
We can do the testing, no problem.

**Comment by partouf** [comment]
Hmm, so no 19.1 - but hope the new ones will do either way

**Comment by rscohn2** [comment]
Thanks!
