### ISSUE TITLE
CTRE needs to be updated to pick up "main" and not "master"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#391]

**Comment by mattgodbolt** [comment]
(or at least I think that's the issue; might be a config change in the other repo.

```
Sep/10 20:26 admin-node/o/c/l/ctre $ ls
dfa/  ecma-unicode/  master/  v2/
```

though might need a one-off manual rename of `master->main` and then change the relevant info?

**Comment by partouf** [comment]
Usually, we use `nightlyclone` and call it `trunk`, which just fetches the default and everything will still work then. But in this we explicitly used a branch checkout of `master` https://github.com/compiler-explorer/infra/blob/master/bin/yaml/libraries.yaml#L760 . (types were based on actual code that was used in the old script files)

I just changed the branchname to main, as I expect we won't have to change it.

**Comment by partouf** [comment]
live now

**Comment by mattgodbolt** [comment]
Thanks!
