### ISSUE TITLE
CTRE DFA branch is (probably) not correct

### ISSUE THREAD

**Issue by hanickadot** [compiler-explorer/infra#394]
This should be able to compile:
https://compiler-explorer.com/z/3ndG45

but I'm getting error:
```
<source>: In function 'bool match(std::string_view)':
<source>:4:22: error: 'fast_match' is not a member of 'ctre'
    4 |         return ctre::fast_match<"aloha|[a-z]+">(sv);
      |                      ^~~~~~~~~~
Compiler returned: 1
```

but the "function" `fast_match` is available in the dfa branch thru `include/ctre.hpp` which includes `ctre/functions.hpp`, I tried to trigger an error and notice the `functions.hpp` is different version than the one in the dfa branch, it looks like od main/master branch.

**Comment by hanickadot** [comment]
Also, please check `ecma-unicode` and `v2` branch.

**Comment by partouf** [comment]
Hm, DFA should be pulled every night, but perhaps that's broken somehow.
Ecma-unicode and v2 are not updated nightly, so we should probably change that as well then.

**Comment by mattgodbolt** [comment]
the DFA branch is in a weird state: maybe it was force-pushed to and we didn't handle it:

```
Sep/14 13:48 admin-node/o/c/l/c/d/include (dfa↑16↓25|✔) $ git status
On branch dfa
Your branch and 'origin/dfa' have diverged,
and have 16 and 25 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

I'll manually reset them

**Comment by mattgodbolt** [comment]
Seems it's just the dfa branch (though as @partouf says we don't update the others nightly):

```
Sep/14 13:50 admin-node/o/c/l/ctre $ ls
dfa/  ecma-unicode/  main/  v2/
Sep/14 13:50 admin-node/o/c/l/ctre $ git -C dfa status
On branch dfa
Your branch and 'origin/dfa' have diverged,
and have 16 and 25 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
Sep/14 13:50 admin-node/o/c/l/ctre $ git -C ecma-unicode/ status
On branch ecma-unicode
Your branch is up to date with 'origin/ecma-unicode'.

nothing to commit, working tree clean
Sep/14 13:50 admin-node/o/c/l/ctre 0.7s $ git -C main status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Sep/14 13:50 admin-node/o/c/l/ctre $ git -C v2 status
On branch v2
Your branch is up to date with 'origin/v2'.

nothing to commit, working tree clean
```

**Comment by mattgodbolt** [comment]
The example now compiles: leaving this open as a reminder to pull v2 and ecma-unicode nightly (and to fix handling force pulling).

**Comment by partouf** [comment]
can kind of reproduce by doing git checkout hash manually and then doing the install, git pull doesn't fix anything there either..

wonder if maybe we should be doing git pull origin branch just to not have these kind of issues anymore.. 

otherwise delete the local copy, but don't know of any way to do that without switch to some other branch first..

/me not a git wiz

**Comment by partouf** [comment]
I guess this works, but seems kind of a hack:

Start
```
partouf@ceub20:/opt/compiler-explorer/libs/ctre/ecma-unicode$ git status
HEAD detached from c867ac2
nothing to commit, working tree clean
```

Existing Step 0: `git fetch + git reset`

Step 1
```
partouf@ceub20:/opt/compiler-explorer/libs/ctre/ecma-unicode$ git checkout origin/ecma-unicode
Previous HEAD position was 4fea9f2 remove unneeded tag
HEAD is now at d20123f support for operator"" in GCC10
```

Step 2
```
partouf@ceub20:/opt/compiler-explorer/libs/ctre/ecma-unicode$ git branch -D ecma-unicode
Deleted branch ecma-unicode (was d20123f).
```

Step 3
```
partouf@ceub20:/opt/compiler-explorer/libs/ctre/ecma-unicode$ git checkout ecma-unicode
Branch 'ecma-unicode' set up to track remote branch 'ecma-unicode' from 'origin'.
Switched to a new branch 'ecma-unicode'
```

Result
```
partouf@ceub20:/opt/compiler-explorer/libs/ctre/ecma-unicode$ git status
On branch ecma-unicode
Your branch is up to date with 'origin/ecma-unicode'.

nothing to commit, working tree clean
```

**Comment by partouf** [comment]
all branches are now updated nightly with some hackery
