### ISSUE TITLE
Daily library install issue

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#414]
```
Cronic detected failure or error output for the command:
bash -c /home/ubuntu/infra/update_compilers/install_libraries.sh nightly

RESULT CODE: 1

ERROR OUTPUT:
Could not access submodule 'doc/html'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 178, in main
    if installable.install():
  File "/home/ubuntu/infra/bin/lib/installation.py", line 509, in install
    self.stage()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 490, in stage
    self.clone_default()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 471, in clone_default
    subprocess.check_call(['git', '-C', dest, 'fetch', '-q'], cwd=self.install_context.staging)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', '-C', '/opt/compiler-explorer/libs/outcome', 'fetch', '-q']' returned non-zero exit status 1.
```

**Comment by mattgodbolt** [comment]
Reproducible with:

```
$ ce_install --enable nightly install outcome
````

**Comment by mattgodbolt** [comment]
Only on the admin node^

Locally:
```
...
Submodule 'include/outcome/status-code' (https://github.com/ned14/status-code.git) registered for path 'include/outcome/experimental/status-code'
Cloning into '/opt/compiler-explorer/libs/outcome/doc/html'...
...
```
so there's something up with the submodules. Will kill and recreate on admin

**Comment by mattgodbolt** [comment]
found only this: https://gitlab.com/gitlab-org/gitlab/-/issues/27287

doc/html _is_ there. will rm -rf it

**Comment by mattgodbolt** [comment]
RM'd it, submodule init, update, fetch...all the things. no luckl

```
 git fetch -a
Fetching submodule doc/html
Fetching submodule include/outcome/experimental/status-code
Could not access submodule 'doc/html'
# git submodule
 d5dddec52921921f1816a4e8d3c3cbec73ce8cc4 doc/html (d5dddec52)
 6ec0fbcdaa585a62631c722dc5452c7f0ceff0fb doc/src/themes/boostdoc (heads/master)
 1d12f5733354d9bd4e19e439f068bdc3cfdabe4f doc/src/themes/docdock (v1.1-10-g1d12f57)
 b70d070c02fe74f85d1a05f91b1d8c1dbf7168b0 include/outcome/experimental/status-code (heads/master-50-gb70d070)
# git fetch -q
Could not access submodule 'doc/html'
```

Will blow away completely. @ned14 - any ideas what might have happened recently to put `git` into this bad state?

**Comment by ned14** [comment]
Looks like I forgot to push something. Weird the CI didn't report it. Sorry. Two secs ...

**Comment by mattgodbolt** [comment]
```
Submodule 'include/outcome/status-code' (https://github.com/ned14/status-code.git) registered for path 'include/outcome/experimental/status-code'
Cloning into '/opt/compiler-explorer/libs/outcome/doc/html'...
Submodule path 'doc/src/themes/boostdoc': checked out '6ec0fbcdaa585a62631c722dc5452c7f0ceff0fb'
Submodule path 'doc/src/themes/docdock': checked out '1d12f5733354d9bd4e19e439f068bdc3cfdabe4f'
Submodule path 'include/outcome/experimental/status-code': checked out 'e01d5f10fe9037873d17b8d071f1af659a7a6b0d'
2020-10-08 13:19:12,111 lib.installation INFO     libraries/c++/nightly/outcome trunk installed OK
1 packages installed OK, 0 skipped, and 0 failed installation
```

going from clean "works" :)

**Comment by mattgodbolt** [comment]
Thanks @ned14 :+1:

**Comment by ned14** [comment]
I just reconciled the git subrepo SHAs in a push there, each of the nested subrepos had wandered ahead of the SHA in their parent repos. But that is absolutely safe and fine, and indeed was intentional of me to have done that.

So your failure is really weird. You're definitely doing a git submodule checkout of all nested submodules right? And not doing something weird like checking out tips shallowly, then finding the non-tip parent SHA isn't found?

**Comment by mattgodbolt** [comment]
Yes to all those things: looks like we hit a git bug (see above). Our setup is complex; but shouldn't be doing anything too silly. It's broken down a little to handle an occasional "force push" on the remote end of libs: https://github.com/compiler-explorer/infra/blob/68b75f6ed0bcb5168d06bde367d0c7c88eaa241f/bin/lib/installation.py#L465-L475 - if you see anything untoward, do say! Thanks!

**Comment by ned14** [comment]
> Yes to all those things: looks like we hit a git bug (see above). Our setup is complex; but shouldn't be doing anything too silly. It's broken down a little to handle an occasional "force push" on the remote end of libs:

I do, very occasionally squash history on the gh-pages branch because it reduces the clone time for everybody by throwing away an unneeded 80% of the repo's size.

> https://github.com/compiler-explorer/infra/blob/68b75f6ed0bcb5168d06bde367d0c7c88eaa241f/bin/lib/installation.py#L465-L475
> 
> - if you see anything untoward, do say! Thanks!

Shouldn't the last line be:

```c++
       subprocess.check_call(['git', '-C', dest, 'submodule', 'update', '--init', '--recursive'], cwd=self.install_context.staging)
```

Outcome has status code and itself as git submodules. status code then has itself as a git submodule as well. So you'd need a recursive submodule update to get all of it.

**Comment by mattgodbolt** [comment]
That could be it: this issue has returned. It still seems odd that we get into this broken state:
```
Installing libraries/c++/nightly/outcome trunk
Could not access submodule 'doc/html'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/infra/bin/lib/ce_install.py", line 178, in main
    if installable.install():
  File "/home/ubuntu/infra/bin/lib/installation.py", line 509, in install
    self.stage()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 490, in stage
    self.clone_default()
  File "/home/ubuntu/infra/bin/lib/installation.py", line 471, in clone_default
    subprocess.check_call(['git', '-C', dest, 'fetch', '-q'], cwd=self.install_context.staging)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', '-C', '/opt/compiler-explorer/libs/outcome', 'fetch', '-q']' returned non-zero exit status 1.
```

Making it `--recursive` does seem to fix it: thanks again @ned14
