### ISSUE TITLE
Something to automatically do 1-off builds

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#423]
It's a tad annoying to having to login to admin, alter some things manually and run the builder. I know it doesn't happen That often, but it would be nice if there was something we could do here.

Perhaps we can have the install script command that check if the version's txz has been uploaded to S3, and if not, start the right builder with the appropriate parameters.

**Comment by partouf** [comment]
Howto add a self-hosted-runner: https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

**Comment by mattgodbolt** [comment]
We now also have the one-off at https://github.com/compiler-explorer/compiler-workflows/actions/workflows/bespoke-build.yaml - which we could move here to keep it out of harm's way for all the daily builds. Thoughts?

**Comment by partouf** [comment]
oh Right, I already forgot we had that. @dkm prepared a bunch of cross compilers but it not being scalable from the current infra workflow was a tad annoying. I think it's a good idea to have it here if it's not too much trouble. Otherwise we can probably learn to use the other repo

**Comment by mattgodbolt** [comment]
Cool! I'll happily move it here. We'd have to see if it works for cross compilers (I think it ought to). I'm not quite sure what you mean by scalable. If you mean it's annoying to have to click 90 times to set off a biuld I agree :D We can add a `ce build` command or similar perhaps that triggers a set of builds?

**Comment by partouf** [comment]
> Cool! I'll happily move it here. We'd have to see if it works for cross compilers (I think it ought to). I'm not quite sure what you mean by scalable. If you mean it's annoying to have to click 90 times to set off a biuld I agree :D We can add a `ce build` command or similar perhaps that triggers a set of builds?

No I meant because it uses the 1 builder-instance you have to wait for an hour until the build is done and then start another one. That's no longer the case with bespoke-build, right?

**Comment by mattgodbolt** [comment]
Oh! Yes: absolutely, we can queue up a ton of builds and they'll complete with up to 4 running at once now!

**Comment by mattgodbolt** [comment]
See 11169f5f4960a41ec62205ecab76670cc9df681b -- and if you have a cross-compiler test we can do we should see if it works for that. I think it ought to...
