### ISSUE TITLE
ce_install doesn't work on mac

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#479]
At least `bin/ce_install` doesn't:

```
➜  infra-claremacrae git:(main) ./bin/ce_install --help
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

(via @claremacrae)

I'm not sure if there's anything else that would work, but we could try it. Of course, the compiler binaries installed are for linux, but for testing libraries it might be nice to have it work (or print out a "sorry, doesn't work on Mac")

**Comment by claremacrae** [comment]
Please don't fix this on my behalf - I'm happy to run CE on a Linux VM, on the rare occasions I'll be running it.

**Comment by partouf** [comment]
https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by partouf** [comment]
tried to see if a simpler `$(realpath $(dirname ${BASH_SOURCE[0]})/..)` would work, but mac doesn't have a `realpath` executable it seems
