### ISSUE TITLE
Ce_install slightly broken if started with sudo on admin node

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#490]
:(
Had to sudo bin/ce_install from infa

Not sure what causes it, will need to see what paths are outputted when using sudo.

**Comment by mattgodbolt** [comment]
We lost one of the readlinks in our python shim - will fix :)

**Comment by apmorton** [comment]
Fixed in dae716f094213eeedb591a0f31c7be7236a4448a

We rely on the `readlink -f` behavior on the admin nodes, but most users won't need it.
So the easiest solution is to just detect mac and use the "legacy" behavior.
