### ISSUE TITLE
Nightly Swift is broken: "libncurses.so.5: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by zhuowei** [compiler-explorer/infra#573]
To reproduce:

1. open Compiler Explorer
2. choose Swift
3. choose x86-64 swiftc nightly

Expected: the sample code compiles
Actual: `/opt/compiler-explorer/swift-nightly/usr/bin/swift-driver: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`

**Comment by partouf** [comment]
Known issue -> https://github.com/compiler-explorer/compiler-explorer/issues/2692

**Comment by zhuowei** [comment]
Can confirm this works now. Thanks!
