### ISSUE TITLE
New compiler build system finishing touches

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#638]
To consider the build stuff done:
* [ ] all builds working (flang broken)
* [ ] libraries moved over
* [ ] ensure non-build.sh stuff adheres to the new "ABI" with a directory output
* [ ] ad hoc builds added (cross and misc at least)
* [ ] kill the old build-status.html (redirect to the new one)
* [ ] decom the builder node
* [ ] get rid of the S3 support in the various images
* [ ] combine the ce-ci and infra repos, taking care not to check in secrets

**Comment by mattgodbolt** [comment]
Future work:
* [ ] daily squash?

**Comment by partouf** [comment]
Concerning library building the following things have to be taken into account:
* Should occur after libraries have been installed/updated
* Should occur after newly built compilers have been installed
