### ISSUE TITLE
install_binaries.sh didn't seem to update

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#66]
seems like the daily job didn't run install_binaries, and so only when I ran it manually did node get updated (change checked in Jan 7th)

**Comment by apmorton** [comment]
this seems to have been fixed at some point:
https://github.com/compiler-explorer/infra/blob/b1591feecafce40942a6a66b7211b2bac9a7d4cd/crontab.root.admin#L5
