### ISSUE TITLE
Give MS a way to grab the current SHA of the deployed version

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#667]

**Comment by RubenRBS** [comment]
https://godbolt.org/api/version returns the gitReleaseName (https://github.com/compiler-explorer/compiler-explorer/blob/ef74c3aa0ea46dadab92d5571f3615d2b9290ada/lib/handlers/api.js#L100 ) would that work?

**Comment by mattgodbolt** [comment]
Perfectly yes!
