### ISSUE TITLE
Add new RISC-V compilers

### ISSUE THREAD

**Issue by dkm** [compiler-explorer/infra#718]
Latest change in gcc-cross-builder introduce new risc-v GCC versions:
https://github.com/compiler-explorer/gcc-cross-builder/commit/1105fbe7c0fa54168f5d63591f1667a0cbf0ce9e

Need to add corresponding changes here for :GCC 8.5.0, 9.4.0, 10.3.0, 11.2.0

Will take care of this, creating this issue to avoid forgetting about it.

**Comment by dkm** [comment]
Keeping track of compiler builds:
- [ ] riscv32 8.5.0
- [ ] riscv32 9.4.0
- [ ] riscv32 10.3.0
- [ ] riscv32 11.2.0
- [ ] riscv64 8.5.0
- [ ] riscv64 9.4.0
- [ ] riscv64 10.3.0
- [ ] riscv64 11.2.0

**Comment by dkm** [comment]
FYI @cmuellner , the compilers you pushed last March should be online shortly. I'll see later to add latest GCC12 to some cross targets later.

**Comment by cmuellner** [comment]
Sounds great!
Let me know if it helps if I provide riscv32/riscv64 patches for GCC 12.1.

**Comment by dkm** [comment]
It sure helps if you provide patches in gcc-cross-build with ct-ng configs for GCC12. I can take of merging, building the compilers and updating various config file!

**Comment by cmuellner** [comment]
I just noticed that ct-ng does not have GCC 12.1 support yet. I created an initial patch for that, and once that builds fine, I'll file a PR to the ct-ng repo (and link to that from here).

**Comment by dkm** [comment]
Thanks @cmuellner ! That will probably help me with adding GCC12 for other targets too :)

**Comment by cmuellner** [comment]
PR for GCC 12.1 support in ct-ng: https://github.com/crosstool-ng/crosstool-ng/pull/1739

**Comment by cmuellner** [comment]
RISC-V support for GCC 11.3.0 and 12.1.0 can be found here:
https://github.com/compiler-explorer/gcc-cross-builder/pull/26
https://github.com/compiler-explorer/gcc-cross-builder/pull/27
