### ISSUE TITLE
Multiple filters block all installables

### ISSUE THREAD

**Issue by tylerh111** [compiler-explorer/infra#719]
Specifying one filter on the command line will correctly apply that filter. However, if multiple filters are specified, nothing is installed/listed. The following examples do not print any targets out:
```bash
./bin/ce_install list "compilers" "libraries"
./bin/ce_install list "compilers/rust" "compilers/c++"
./bin/ce_install list "compilers/c++/x86/gcc" "compilers/c++/clang"
./bin/ce_install list "compilers/c++/x86/gcc 11.2.0" "compilers/c++/clang 13.0.1"
```
The behavior I would expect is that `ce_install` would run each installable through the filter. I have a branch that exhibits this behavior: https://github.com/compiler-explorer/infra/compare/main...tylerh111:fix-filtering. If this is desired behavior, I can create a pull request.

**Comment by mattgodbolt** [comment]
Yikes, yeah - the filter is `and`-d I think. It's bothered me too :D Thanks for raising this.

**Comment by tylerh111** [comment]
To move some of the discussion on the pull request here...

Right now, I have a flag that switches between the old way of filter conjunction and a new way for filter disjunction. You can see this in the pull request. The original concern was that without a flag, something like `ce_install list x86/gcc 12.1.0` would break (it would return all x86 gcc versions). You would need to wrap the filter in quotes to get current behavior. However, this is only an issue because space is used to delimit the context and target of an installable.

@partouf suggested that we could use some other delimiter. I pointed out that `=` is one of the few characters that are not used in the context or target name. So we could in write something like `ce_install list x86/gcc=12.1.0`. It looks to be a very simple change in code:
https://github.com/compiler-explorer/infra/blob/1c7db41cafd76cb8a126775fc53a1c06bd916eda/bin/lib/ce_install.py#L38
https://github.com/compiler-explorer/infra/blob/1c7db41cafd76cb8a126775fc53a1c06bd916eda/bin/lib/installation.py#L294
However, we would have to change the dependencies listed in the following files: `kotlin-native.yaml`, `kotlin.yaml`, `scala.yaml`. This would also break any scripts that use the space instead of equals. Something to think about for the future I suppose.

**Comment by mattgodbolt** [comment]
Thanks for thinking about this. I could get behind the `=` change; and the yaml changes necessary. @partouf thoughts?

**Comment by partouf** [comment]
I think the = is a decent solution, we can fix breakages in our own scripts.
