### ISSUE TITLE
Add python 3.10 for virtual environment

### ISSUE THREAD

**Issue by tylerh111** [compiler-explorer/infra#724]
Title. This should only affect the make file for checking which version of python is installed. Would it be possible to check for a minimum python version number? I assume the minimum python version is 3.8.

**Comment by dkm** [comment]
Yes, I had the same issue as python3.8 is not part of Debian sid anymore

**Comment by partouf** [comment]
3.8 is a minimum, I know 3.7 doesn't work

The code to detect the version is here https://github.com/compiler-explorer/infra/blob/main/Makefile#L3
I'm not sure how to make it a minimum version.

We could "just" use the python3 link, but that might also be pointing to an old version, which is then not what we want.

**Comment by partouf** [comment]
I just added 3.10 as an option.
I can't install 3.10 on my OS, but I tried 3.9 and it worked for that.

Can you see if it works with this change?

**Comment by dkm** [comment]
Works nicely here, it picks 3.10 (I have 3.10 and 3.9 installed)

**Comment by tylerh111** [comment]
This is exactly what I had to do for my installation. Thank!
