### ISSUE TITLE
Required Ninja copy change

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#880]
Change https://github.com/compiler-explorer/infra/blob/c01a69754a5cdc763e1558744dd8016e02021ae6/init/start.sh#L92 to copy the actual binary and not the link.

`readlink -f /opt/compiler-explorer/ninja/ninja` etc

**Comment by partouf** [comment]
and then make a new AMI

**Comment by mattgodbolt** [comment]
ninja is only tiny - does it really need to be copied locally? Can't we install it on `/opt/compiler-explorer` like the compilers etc? it'll be squashfs's and all that

**Comment by partouf** [comment]
Well it needs to be in the PATH whatever it would be, so there's a difference between it and compilers

**Comment by mattgodbolt** [comment]
I'm pretty sure it can be configured to be anywhere; but this also works.

**Comment by mattgodbolt** [comment]
not that I can find the config now...so...! Nothing to see here, move along, please continue :)

**Comment by partouf** [comment]
Would've been easier to call `ninja` ourselves, but I chose to swap to `cmake --build` instead because that's easier in CE configuration
