### ISSUE TITLE
Library building

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#925]
Make `has_failed_before()` either correct or remove it
https://github.com/compiler-explorer/infra/blob/29af1bdf36b8da9f4374f6756589f3e179d71e07/bin/lib/library_builder.py#L681

Some libraries haven't been building even though they are compilertrunk / librarytrunk

Catch2 trunk for Clang trunk is even 2 years old, it's a little crazy

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/4573

**Comment by RubenRBS** [comment]
> Catch2 trunk for Clang trunk is even 2 years old, it's a little crazy
oh wow

**Comment by partouf** [comment]
I think the function can be fixed if we store the git commit hash with the failed build in our sqlite database

So add commithash parameter to https://github.com/compiler-explorer/conanproxy/blob/main/build-logging.js#L68 and https://github.com/compiler-explorer/conanproxy/blob/main/build-logging.js#L128

I think it involves creating an alter table script here https://github.com/compiler-explorer/conanproxy/tree/main/migrations

but not totally remember on how the migration stuff works
