### ISSUE TITLE
Deletion of old builds broken

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/infra#947]
deletes wintest builds eventhough they should be in use

**Comment by partouf** [comment]
looking at this now because its a little confusing, but I think I know what's going on;

```
Mar/06 17:55 admin-node~ 2.0s $ ce --env wintest builds list
WARNING:root:Ignoring broken key dist/gh/cewrapper-config/6443.zip
WARNING:root:Ignoring broken key dist/gh/cewrapper-config/6456.zip
WARNING:root:Ignoring broken key dist/gh/cewrapper-config/6577.zip
WARNING:root:Ignoring broken key dist/gh/main/5731.zip
Live  Branch     Version    Size       Hash
      main       gh-5887    54.7MiB    c5585f..43754b
```

These warnings are given because the zip files are still there, but the .txt and .tar.xz have disappeared.

That means 2 things:
1. The check for in-use is not correct (because for example gh-5887 is in use, but the .tar.xz has been deleted, so its confused (though the .zip and .txt still exist, so the Windows environments will still work)
2. When it does decide to delete, it does so only partial; the .txt file has disappeared, but not the .zip

**Comment by mattgodbolt** [comment]
Ugh I am sorry! thanks for taking a look

**Comment by mattgodbolt** [comment]
I'll look tonight though

**Comment by mattgodbolt** [comment]
Oh?! The .zip thing is new right!?! I thought this was something broken in the tarball stuff but then I realised it's the zipfile thing!

**Comment by mattgodbolt** [comment]
Recusing myself but if you need a hand I can take a look (I had misread as yet another cockup of mine in the build handling...)

**Comment by partouf** [comment]
> Oh?! The .zip thing is new right!?! I thought this was something broken in the tarball stuff but then I realised it's the zipfile thing!

Yes, its for the windows builds. I'm gonna try to fix it tonight. I probably missed something when I changed the code for the .zips

**Comment by mattgodbolt** [comment]
Is this now fixed? I think so, right? :)

**Comment by partouf** [comment]
I haven't checked... but.. in theory yes.. haven't seen the error message again at least

**Comment by partouf** [comment]
havent seen this in a while, definitely fixed
