### ISSUE TITLE
Windows prom agent didn't start up

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/infra#971]
I autoscaled us to 3 nodes and only the original node was logging:

https://ce.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22up%7Benv%3D%5C%22winprod%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

this showed only one host. I could see the other hosts were up and heatlhy and the load balancer was seemingly giving them traffic, but the count of up nodes was still `1` and there were no stats that I could see being logged from the new nodes.

**Comment by mattgodbolt** [comment]
https://ce.grafana.net/d/2W9_lB5Mk/compiler-explorer-dashboard?orgId=1&from=1679170769735&to=1679173048162 shows this - the aws stats show 3 win instances but the "all instance types" which uses the prom stats show only 1

**Comment by partouf** [comment]
should be fixed
